name: core
description: Common shared code
version: 0.0.1
#homepage: https://www.example.com
#author: ironman <email@example.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  bloc: ^2.0.0
  bloc_event: ^1.0.5
  intl: any
  http: ^0.12.0
  equatable:
  uuid:

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
