name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Ryan <ryan@superformula.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  angular: ^5.0.0
  angular_components: ^0.13.0
  angular_router:
  core:
    path: ../core
  angular_bloc:

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ">=1.6.2 <2.0.0"
  build_test: ^0.10.8
  build_web_compilers: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
